### ISSUE TITLE
Does not load on PowerShell Core

### ISSUE THREAD

**Issue by corbob** [MichaelJolley/ps-alias#14]
Renamed file to psm1 in an attempt at a start for #12 when trying to import into PowerShell Core, get errors regarding the `Get-WmiObject` calls as these cmdlets are not available in PowerShell Core. An alternative would be the cim cmdlets, but IIRC that's not cross platform as the cim cmdlets don't exist on `-not $IsWindows`. A more robust alternative may be to use `Get-Process` as IIRC it exists across the board.

**Comment by parithon** [comment]
I believe this has been solved when converted into a module.

**Comment by corbob** [comment]
Looks like it.

![Module successfully imported into PowerShell Core](https://user-images.githubusercontent.com/30301021/60317416-d8b29c80-9923-11e9-94a1-525ed5fe3902.png)
