### ISSUE TITLE
Need to update README.md with installation instructions

### ISSUE THREAD

**Issue by michaeljolley** [MichaelJolley/ps-alias#37]
We can certainly add a link to the PowerShell Gallery page at `https://www.powershellgallery.com/packages/devtoolbox`, but beyond that, the user needs to add `Import-Module devtoolbox` at the top of their profile.ps1.

I'd be interested in if there's a better way to install that would automatically add it to the profile.  @brettmillerb or @corbob?

**Comment by corbob** [comment]
`Install-Module devtoolbox` should add it to the `$PSModulePath` in which case it should auto-load when first needed...

**Comment by michaeljolley** [comment]
I wonder if it doesn't because I've got a customized profile.ps1?

**Comment by parithon** [comment]
Technically you shouldn't need to import the module because PowerShell will do that on your behalf if you try to use one of the registered functions.

**Comment by brettmillerb** [comment]
> We can certainly add a link to the PowerShell Gallery page at `https://www.powershellgallery.com/packages/devtoolbox`, but beyond that, the user needs to add `Import-Module devtoolbox` at the top of their profile.ps1.
> 
> I'd be interested in if there's a better way to install that would automatically add it to the profile. @brettmillerb or @corbob?

the problem you have there is that there are multiple profiles.

I use `$Profile.CurrentUserAllHosts` whereas a lot of people just use `$Profile`

But as @parithon said, it will auto-load the module when you try to use one of the commands as long as you are on PowerShell v3+.

**Comment by michaeljolley** [comment]
I'm just going to add a section on the README.md that, like @brettmillerb suggested, links to the PowerShell Gallery.
