### ISSUE TITLE
The contributing guide seems to be outdated

### ISSUE THREAD

**Issue by digitaldrummerj** [MichaelJolley/ps-alias#51]
I wanted to add the git diff command but I was not able to the module build working.  The contributing guide appears to be outdated since the files it says to run are no longer in the src folder.

**Comment by digitaldrummerj** [comment]
@MichaelJolley any update on getting the contributing guide updated?  I would like to submit a few commands to the devtoolbox but am in a holding pattern.

**Comment by michaeljolley** [comment]
Thanks for pointing that out. There were several old things in there and the README. I think it's updated and ready to go.
